# categorie Chinese, Japanese, Indian, Persian, African, Osteria, Farmhouse, Café, Pizzeria
category = ['chinese', 'japanese', ' indian', 'persian', 'african', 'osteria', 'farmhouse']

restaurants = {"indian" : [["Krishna 13", "4.3/5", "$$-$$$", "Via Foscolo 13 Piazza Vittorio, 00185 Roma Italia"], 
                           ["Himalaya's Kashmir", "4.5/5", "$$-$$$", "Via Principe Amedeo 325/327 00185 Roma Italia"], 
                           ["Jaipur", "4.4/5", "$$-$$$", "Via Di San Francesco A Ripa, 56 00153 Roma Italia"], 
                           ["Annapoorna India", "4.7/5", "$$-$$$", "Via Emanuele Filiberto 136, 00185 Roma Italia"], 
                           ["Gandhi 2", "4.5/5", "$$-$$$", "Via Genova 29/A, 00184 Roma Italia"], 
                           ["Ristorante Indiano Bombay", "4.2/5", "$$-$$$", "Via Cerveteri 25/27 Re Di Roma, 00183 Roma Italia"], 
                           ["Gandhi", "4.4/5", "$$-$$$", "Via Pellegrino Matteucci 124, 00154 Roma Italia"]],
               "chinese" : [["Dumpling Bar", "4.6/5", "$", "Piazza Meucci 1, 00146 Roma Italia"], 
                            ["JiaMo.Lab", "4.8/5", "$", "Via Bergamo 15, 00198 Roma Italia"], 
                            ["Ristorante Lin", "4.5/5", "$$-$$$", "Via Basento 70, 00198 Roma Italia"], 
                            ["Ristorante Taste East", "4.4/5", "$$-$$$", "Piazza del Sacro Cuore 12-15, 00151 Roma Italia"], 
                            ["Ristorante Sichuan", "4.4/5", "$$-$$$", "Via di San Martino Ai Monti 33/C, 00184 Roma Italia"]],
               "japanese" : [["Ramè Sushi Naturale Italiano", "4.9/5", "$$-$$$", "Via Falco Portinari 33, 00151 Roma Italia"], 
                             ["Tora Sushi & Asian Cuisine", "4.7/5", "$$-$$$", "Corso del Rinascimento 71, 00186 Roma Italia"], 
                             ["Sushita", "4.6/5", "$$-$$$", "Via Nomentana 1051, 00137 Roma Italia"], 
                             ["Ramen Bar Akira", "4.5/5", "$$-$$$", "Via in Arcione 71, 00187 Roma Italia"], 
                             ["Sushisen", "4.5/5", "$$-$$$", "Via Giuseppe Giulietti 21A, 00154 Roma Italia"]],
               "persian" : [["Ristorante Periano", "4.3/5", "$$-$$$", "Via di Grottarossa 52, 00189 Roma Italia"], 
                            ["Taberna Persiana", "4/5", "$$-$$$", "Via Ostiense 36/H,, 00154 Roma Italia"], 
                            ["Ristorante Tanur", "3.8/5", "$$-$$$", "Via Chiana 54-56 Zona Coppedé, 00198 Roma Italia"], 
                            ["Ariya Iranian Restaurant", "5/5", "$", "Via dell'Aquila Reale 8, 00169 Roma Italia"]],
               "african" : [["Gustamundo Bistrot Sede Cipro" "4.7/5", "$$-$$$", "Via Sebastiano Ziani 58, 00136 Roma Italia"], 
                            ["Ristorante Africano Etiope Enqutatash", "4.5/5", "$$-$$$", "Viale Della Stazione Prenestina 55, 00177 Roma Italia"], 
                            ["Lime Restaurant&Bar", "4.4/5", "$$-$$$", "Via Ancona 33/35, 00198 Roma Italia"], 
                            ["Sahara", "4.2/5", "$$-$$$", "Viale Ippocatre 43, 00161 Roma Italia"], 
                            ["Ristorante Eritrea", "4.3/5", "$", "Piazza Del Gazometro 1, 00154 Roma Italia"]],
               "osteria" : [["Riccioli D'oro", "4.7/5", "$$-$$$", "Via Conca d'Oro 38, Roma italia"], 
                            ["Osteria Flaminio", "4.5/5", "$$-$$$", "Lungotevere flaminio 63/d, Roma Italia"], 
                            ["Osteria Gnocco", "4.4/5", "$$-$$$", "Via della Scrofa 100, Roma"], 
                            ["Animella Osteria Romana", "4.4/5", "$$-$$$", "Via dei Gelsi 96, Roma"], 
                            ["Checco er carattiere", "4.4/5", "$$-$$$", "Via Benedetta 10, Roma Italia"]],
               "farmhouse" : [["Colle Tocci", "4.3/5", "$$-$$$", "Contrada Castagnola 8, 00028 Subiaco RM"], 
                              ["Tenuta Monte la Guardia", "4.4/5", "$$", "Localitá Monte la Guardia, 00062 Castel Giuliano RM"], 
                              ["La Vecchia Fattoria", "4.5/5", "$$-$$$", "SP59 & Via Amerina, 01028 Orte VT"], 
                              ["La Cerquetta", "4.2/5", "$$-$$$", "Via di Quarto Conca 208, 00013"], 
                              ["La Baita", "4.4/5", "$$-$$$", "Via Panzanata 2, 00062 Castel Giuliano RM"]],
               "café" : [["Sant'Eustachio", "4.5/5", "$-$$$", "Piazza Sant'Eustaccio 82, Roma Italia"], 
                         ["La Casa Del Caffè Tazza d'Oro", "4.5/5", "$-$$$", "Via degli Orfani 84, Roma Italia"], 
                         ["Castroni", "4.5/5", "$$-$$$", "Via Cola di Rienzo 196, Roma Italia"], 
                         ["Antico Caffè della Pace", "4.5/5", "$-$$$", "Via della Pace 3/7, Roma Italia"], 
                         ["Antico Caffè Greco", "4.5/5", "$-$$$" "Via dei Condotti 86, Roma Italia"]],
               "pizzeria" : [["Sforno", "4.5/5", "$$-$$$", "Via Statilio Ottato 110/116, Roma Italia"], 
                             ["La Gatta Mangiona", "4/5", "$$-$$$", "Via F.Ozanam 30-32, 00152 roma Italia"], 
                             ["Pizzeria Ciro Cascella", "4.4/5", "$$-$$$", "Viale Isacco Newton 68, 00151 Roma Italia"], 
                             ["Lievito Madre Roma - Gino Sorbillo", "4.5/5", "$$-$$$", "Piazza Augusto Imperatore 46, Roma Italia"], 
                             ["Pizzium", "4.6/5", "$$-$$$", "Via Piave 9, 00187 Roma Italia"]] 
              }